package com.v01.techgear_server.enums;

public enum UserPermission {
    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    ORDER_PROCESS,
    ORDER_READ,
    ORDER_CREATE,
    ORDER_UPDATE,
    ORDER_READ_OWN,

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    PROFILE_READ_OWN,
    PROFILE_UPDATE_OWN,


    REVIEW_CREATE,
    REVIEW_READ_OWN,
    REPORT_GENERATE,

    ACCESS_ADMIN_PANEL,
    USER_MANAGE,
    PRODUCT_MANAGE,
    ORDER_MANAGE,
    DISCOUNT_MANAGE,
    INVENTORY_MANAGE,

    CUSTOMER_SUPPORT_ACCESS,
    CUSTOMER_SUPPORT_MANAGE,

    SALES_PERFORMANCE_VIEW,
    STAFF_MANAGE,
    REPORT_VIEW_ALL,
}
